name: ci
on:
  pull_request:
  push:
    branches:
      - master
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            generator: Ninja
            compiler: msvc
          - os: ubuntu-latest
            generator: Ninja
            compiler: gcc
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Formatting
        run: |
          choco install -y llvm
          $CLANG_FORMAT_DIFF = git diff --name-only --diff-filter=d HEAD~1
          foreach ($FILE in $CLANG_FORMAT_DIFF) {
            if ($FILE -match ".*\.(cpp|h)$") {
              $formatOutput = clang-format.exe -style=file -output-replacements-xml $FILE
              if ($formatOutput -match "<replacement ") {
                Write-Host "File $FILE is not formatted correctly. Please run clang-format."
                exit 1
              }
            }
          }
          
      - name: Setup Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt-get install ninja-build libgl1-mesa-dev libegl1-mesa-dev xorg-dev libglu1-mesa-dev
          
      - name: Setup Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco upgrade visualstudio2022buildtools
        
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/cpm-cache
          key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
          restore-keys: |
            ${{ runner.os }}-cpm-


      - name: Configure CMake
        run: |
          cmake -DCPM_SOURCE_CACHE=~/cpm-cache -S . -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Ninja"
          
      - name: Build CMake
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cmake --build ./build -j 14

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute tests defined by the CMake configuration.
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}
