name: ci
on:
  pull_request:
  push:
    branches:
      - master
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          # - macos-12
        generator:
          - Ninja
        compiler:
          - llvm
          - gcc
          # you can specify the version after `-` like `llvm-13.0.0`.
        include:
          - os: "windows-latest"
            compiler: "msvc"
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/cpm-cache
          key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
          restore-keys: |
            ${{ runner.os }}-cpm-

      - name: Configure CMake
        run: |
          cmake -DCPM_SOURCE_CACHE=~/cpm-cache -S . -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D CMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_COMPILER_LAUNCHER=${{ matrix.compiler.cc }} -G "Ninja"
          
      - name: Build CMake
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cmake --build ./build -j 14

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute tests defined by the CMake configuration.
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}
